# Site settings
title: Supervans
description: "Supervans is committed to improving the efficiency of custom electronics technicians. Efficiency is the secret to profitability and growth."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/supervan.png

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Supervans
    hero_description: Supervans provides custom electronics installers the installation materials they require to be efficient and effective in the field. We provide storage and organization systems to ensure installer are always prepared for their jobs.

# Contact form
api_token: d21bc687dbfa8e886d1acc648348255c

# Contact info
contact:
    phone: 1.800.811.1692
    emergency: 931 53 234
    email: info@supervans.co
    address: 5239 Fairmont Street, <br> Vancouver BC V5R 3V4, <br>Canada

# Opening hours
monday_friday: 7:00AM PST – 18:00 PST
saturday: Closed
sunday: Closed

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 5239 Fairmont Street, Vancouver
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype:
feed:

# Footer
copyright: © 2016 Supervans - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
